source 'https://rubygems.org'


gem 'rails', '4.2.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'pg'
gem "ember-rails", github: "emberjs/ember-rails"

group :development, :test do
  gem 'pry-rails'
  gem 'capybara'
  gem 'web-console', '~> 2.0'
  gem 'rspec-rails'
  gem 'spring'
end

group :test do
  gem 'coveralls', require: false
end
